default: &default
  adapter: postgresql
  encoding: unicode
  username: postgres
  password: 1234
  host: postgres
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: jogging_development
test:
  <<: *default
  database: jogging_test

production:
  <<: *default
  database: jogging_production
  host: 127.0.0.1

